CREATE TABLE schema_migrations(version integer PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE users(id text PRIMARY KEY, username text UNIQUE NOT NULL, name text NOT NULL, password_hash text NOT NULL, role text NOT NULL CHECK(role IN ('owner','editor')), active integer NOT NULL DEFAULT 1 CHECK(active IN(0,1)));
CREATE TABLE sessions(token_hash text PRIMARY KEY, user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at bigint NOT NULL);
CREATE INDEX sessions_expiry ON sessions(expires_at);
CREATE TABLE rate_limits(key text PRIMARY KEY,count integer NOT NULL,expires_at bigint NOT NULL);
CREATE TABLE meta(key text PRIMARY KEY,value text NOT NULL);
CREATE TABLE animals(slug text PRIMARY KEY,content jsonb NOT NULL,published integer NOT NULL CHECK(published IN(0,1)),status text NOT NULL CHECK(status IN('available','reserved','adopted')),version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE settings(id integer PRIMARY KEY CHECK(id=1),content jsonb NOT NULL,version integer NOT NULL DEFAULT 1);
CREATE TABLE requests(id text PRIMARY KEY,idempotency_key text UNIQUE NOT NULL,payload_hash text NOT NULL,kind text NOT NULL CHECK(kind IN('contact','meeting')),animal_slug text REFERENCES animals(slug) ON DELETE SET NULL,payload jsonb NOT NULL,status text NOT NULL DEFAULT 'new' CHECK(status IN('new','in_progress','closed')),created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX requests_created ON requests(created_at DESC);
CREATE TABLE request_followup(request_id text PRIMARY KEY REFERENCES requests(id) ON DELETE CASCADE,content jsonb NOT NULL DEFAULT '{}',version integer NOT NULL DEFAULT 1,closed_at timestamptz);
CREATE TABLE request_events(id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,request_id text NOT NULL REFERENCES requests(id) ON DELETE CASCADE,actor text NOT NULL,description text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE media(id text PRIMARY KEY,bytes bytea NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE notifications(id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,request_id text NOT NULL REFERENCES requests(id) ON DELETE CASCADE,audience text NOT NULL CHECK(audience IN('team','applicant')),recipient text NOT NULL,status text NOT NULL DEFAULT 'pending',attempts integer NOT NULL DEFAULT 0,next_attempt bigint NOT NULL DEFAULT 0,provider_id text,error text,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(request_id,audience,recipient));
CREATE TABLE maintenance(key text PRIMARY KEY,value text NOT NULL);
CREATE TABLE documents(id text PRIMARY KEY,title text NOT NULL,category text NOT NULL,status text NOT NULL,html text NOT NULL,search_text text NOT NULL,version integer NOT NULL DEFAULT 1,updated_at timestamptz NOT NULL DEFAULT now(),updated_by text NOT NULL,source_id text UNIQUE,imported_markdown text);
CREATE TABLE revisions(id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,document_id text NOT NULL REFERENCES documents(id) ON DELETE CASCADE,version integer NOT NULL,title text NOT NULL,category text NOT NULL,status text NOT NULL,html text NOT NULL,author text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(document_id,version));
CREATE TABLE tasks(id text PRIMARY KEY,title text NOT NULL,note text NOT NULL DEFAULT '',status text NOT NULL,document_id text REFERENCES documents(id),assignee text REFERENCES users(id),version integer NOT NULL DEFAULT 1,updated_at timestamptz NOT NULL DEFAULT now(),updated_by text NOT NULL);
CREATE TABLE document_publications(document_id text PRIMARY KEY REFERENCES documents(id),revision_id integer NOT NULL REFERENCES revisions(id),slug text NOT NULL UNIQUE,published_at timestamptz NOT NULL DEFAULT now(),published_by text NOT NULL);
CREATE TABLE audit_events(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,actor text NOT NULL,entity text NOT NULL,entity_id text,action text NOT NULL,before_data jsonb,after_data jsonb,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX audit_recent ON audit_events(created_at DESC);
CREATE FUNCTION audit_change() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE before_row jsonb; after_row jsonb; entity_key text;
BEGIN
  IF TG_OP <> 'INSERT' THEN before_row:=to_jsonb(OLD); END IF;
  IF TG_OP <> 'DELETE' THEN after_row:=to_jsonb(NEW); END IF;
  entity_key:=coalesce(after_row->>'id',after_row->>'slug',after_row->>'request_id',after_row->>'document_id',before_row->>'id',before_row->>'slug',before_row->>'request_id',before_row->>'document_id');
  IF TG_TABLE_NAME IN ('requests','request_followup') THEN
    -- Do not retain personal application payloads after a privacy deletion.
    before_row:=jsonb_build_object('id',entity_key,'status',before_row->>'status','version',before_row->>'version');
    after_row:=jsonb_build_object('id',entity_key,'status',after_row->>'status','version',after_row->>'version');
  END IF;
  before_row:=before_row-'imported_markdown'-'search_text'; after_row:=after_row-'imported_markdown'-'search_text';
  INSERT INTO audit_events(actor,entity,entity_id,action,before_data,after_data) VALUES(coalesce(nullif(current_setting('ames.actor',true),''),'Système'),TG_TABLE_NAME,entity_key,TG_OP,before_row,after_row);
  RETURN NULL;
END $$;
DO $$ DECLARE tab text; BEGIN FOREACH tab IN ARRAY ARRAY['animals','settings','requests','request_followup','documents','tasks','document_publications'] LOOP EXECUTE format('CREATE TRIGGER changes AFTER INSERT OR UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION audit_change()',tab); END LOOP; END $$;
INSERT INTO schema_migrations(version) VALUES(1);
